name: 'apt-repo-action'
description: 'Download GitHub organization to a apt repo'
inputs:
  token:
    required: true
  organization:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: radxa-repo/apt-repo-action
        path: .apt-repo-action
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: radxa-repo/freight
        path: .freight
    - name: Run
      shell: bash
      run: |
        cd .freight
        sudo make install
        cd ..
        dotnet run -c Release --project .apt-repo-action/apt-repo.csproj -- ${{ inputs.token }} ${{ inputs.organization }}
        rm -rf .apt-repo-action .freight