name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.cs'
      - '**/*.csproj'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run
      shell: bash
      run: |
        dotnet build
